import { FiClock, FiShield, FiActivity } from "react-icons/fi";

const auditLogs = [
  {
    id: 1,
    action: "Profile updated",
    module: "User Profile",
    severity: "Medium",
    time: "2025-01-30 11:20 AM",
    ip: "192.168.1.12",
  },
  {
    id: 2,
    action: "Password changed",
    module: "Security",
    severity: "High",
    time: "2025-01-28 09:10 AM",
    ip: "192.168.1.10",
  },
  {
    id: 3,
    action: "Logged in",
    module: "Authentication",
    severity: "Low",
    time: "2025-01-27 08:01 AM",
    ip: "192.168.1.8",
  },
];

const severityStyle = {
  High: "bg-red-100 text-red-700",
  Medium: "bg-yellow-100 text-yellow-700",
  Low: "bg-green-100 text-green-700",
};

const UserAuditLogs = () => {
  return (
    <div className="rounded-xl border bg-white p-6">
      <div className="mb-4 flex items-center justify-between">
        <div>
          <h2 className="text-lg font-semibold text-gray-900">
            Audit & Activity Logs
          </h2>
          <p className="text-sm text-gray-500">
            System-tracked user actions (read-only)
          </p>
        </div>
        <FiShield className="text-gray-400" size={22} />
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead className="border-b bg-gray-50 text-gray-500">
            <tr>
              <th className="px-4 py-3 text-left">Action</th>
              <th className="px-4 py-3 text-left">Module</th>
              <th className="px-4 py-3 text-left">Severity</th>
              <th className="px-4 py-3 text-left">Time</th>
              <th className="px-4 py-3 text-left">IP Address</th>
            </tr>
          </thead>

          <tbody>
            {auditLogs.map((log) => (
              <tr key={log.id} className="border-b hover:bg-gray-50">
                <td className="px-4 py-3 flex items-center gap-2 font-medium">
                  <FiActivity className="text-gray-400" />
                  {log.action}
                </td>
                <td className="px-4 py-3">{log.module}</td>
                <td className="px-4 py-3">
                  <span
                    className={`rounded-full px-3 py-1 text-xs font-medium ${severityStyle[log.severity]}`}
                  >
                    {log.severity}
                  </span>
                </td>
                <td className="px-4 py-3 flex items-center gap-2 text-gray-500">
                  <FiClock />
                  {log.time}
                </td>
                <td className="px-4 py-3 text-gray-500">{log.ip}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="mt-4 rounded-lg bg-gray-50 p-3 text-xs text-gray-600">
        🔒 Logs are auto-generated by the system and cannot be edited or deleted.
      </div>
    </div>
  );
};

export default UserAuditLogs;
